# Generated by Django 4.0.5 on 2022-08-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0003_answer_score_alter_answer_id_alter_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='score',
            field=models.FloatField(default=0, null=True),
        ),
    ]
