# Generated by Django 4.0.5 on 2022-08-16 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0005_answer_new_question_new_category_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_new',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QA.question_new'),
        ),
        migrations.AlterField(
            model_name='question_new',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='QA.answer_new'),
        ),
    ]
