# Generated by Django 4.0.5 on 2022-08-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0009_alter_category_new_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_new',
            name='question',
            field=models.ManyToManyField(blank=True, to='QA.question_new'),
        ),
        migrations.AlterField(
            model_name='question_new',
            name='answer',
            field=models.ManyToManyField(blank=True, to='QA.answer_new'),
        ),
    ]
