# Generated by Django 4.0.5 on 2022-08-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0010_alter_category_new_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_new',
            name='text',
            field=models.CharField(default='hadi', max_length=100),
        ),
    ]
